/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUNDdefine = 1,
  anon_sym_POUNDconst = 2,
  sym_identifier = 3,
  sym_integer = 4,
  anon_sym_SLASH_STAR = 5,
  aux_sym_comment_token1 = 6,
  anon_sym_STAR_STAR = 7,
  aux_sym_comment_token2 = 8,
  anon_sym_STAR_SLASH = 9,
  anon_sym_SLASH_STAR_STAR_SLASH = 10,
  anon_sym_SLASH_STAR_STAR_STAR_SLASH = 11,
  sym_source_file = 12,
  sym__definition = 13,
  sym_define_statement = 14,
  sym_const_statement = 15,
  sym_comment = 16,
  aux_sym_source_file_repeat1 = 17,
  aux_sym_comment_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUNDdefine] = "#define",
  [anon_sym_POUNDconst] = "#const",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_STAR_STAR] = "**",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_STAR_SLASH] = "*/",
  [anon_sym_SLASH_STAR_STAR_SLASH] = "/**/",
  [anon_sym_SLASH_STAR_STAR_STAR_SLASH] = "/***/",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_define_statement] = "define_statement",
  [sym_const_statement] = "const_statement",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUNDdefine] = anon_sym_POUNDdefine,
  [anon_sym_POUNDconst] = anon_sym_POUNDconst,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [anon_sym_SLASH_STAR_STAR_SLASH] = anon_sym_SLASH_STAR_STAR_SLASH,
  [anon_sym_SLASH_STAR_STAR_STAR_SLASH] = anon_sym_SLASH_STAR_STAR_STAR_SLASH,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_define_statement] = sym_define_statement,
  [sym_const_statement] = sym_const_statement,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUNDdefine] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDconst] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_STAR_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_STAR_STAR_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_define_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_const_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 15,
  [23] = 13,
  [24] = 14,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(1);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(17);
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUNDdefine);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUNDconst);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '*') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(4);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(26);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(28);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(30);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR_STAR_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR_STAR_SLASH);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(26);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR_STAR_STAR_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR_STAR_STAR_SLASH);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 0},
  [22] = {(TSStateId)(-1),},
  [23] = {(TSStateId)(-1),},
  [24] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUNDdefine] = ACTIONS(1),
    [anon_sym_POUNDconst] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [aux_sym_comment_token2] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_STAR_STAR_SLASH] = ACTIONS(5),
    [anon_sym_SLASH_STAR_STAR_STAR_SLASH] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(19),
    [sym__definition] = STATE(10),
    [sym_define_statement] = STATE(9),
    [sym_const_statement] = STATE(9),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_POUNDdefine] = ACTIONS(9),
    [anon_sym_POUNDconst] = ACTIONS(11),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_SLASH_STAR_STAR_SLASH] = ACTIONS(5),
    [anon_sym_SLASH_STAR_STAR_STAR_SLASH] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(10),
    [sym_define_statement] = STATE(9),
    [sym_const_statement] = STATE(9),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_POUNDdefine] = ACTIONS(9),
    [anon_sym_POUNDconst] = ACTIONS(11),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_SLASH_STAR_STAR_SLASH] = ACTIONS(5),
    [anon_sym_SLASH_STAR_STAR_STAR_SLASH] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym__definition] = STATE(10),
    [sym_define_statement] = STATE(9),
    [sym_const_statement] = STATE(9),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_POUNDdefine] = ACTIONS(17),
    [anon_sym_POUNDconst] = ACTIONS(20),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_SLASH_STAR_STAR_SLASH] = ACTIONS(5),
    [anon_sym_SLASH_STAR_STAR_STAR_SLASH] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(23), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(27), 1,
      anon_sym_STAR_SLASH,
    STATE(4), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_comment_repeat1,
    ACTIONS(25), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(29), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
  [21] = 6,
    ACTIONS(23), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(33), 1,
      anon_sym_STAR_SLASH,
    STATE(5), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_comment_repeat1,
    ACTIONS(29), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    ACTIONS(31), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [42] = 6,
    ACTIONS(23), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(35), 1,
      anon_sym_STAR_SLASH,
    STATE(6), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_comment_repeat1,
    ACTIONS(29), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    ACTIONS(31), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [63] = 5,
    ACTIONS(37), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(43), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(40), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(45), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    STATE(7), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [82] = 6,
    ACTIONS(23), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(50), 1,
      anon_sym_STAR_SLASH,
    STATE(5), 1,
      aux_sym_comment_repeat1,
    STATE(8), 1,
      sym_comment,
    ACTIONS(29), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    ACTIONS(48), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [103] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(9), 1,
      sym_comment,
    ACTIONS(5), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    ACTIONS(52), 3,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDconst,
  [119] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(10), 1,
      sym_comment,
    ACTIONS(5), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDconst,
  [135] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(11), 1,
      sym_comment,
    ACTIONS(5), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    ACTIONS(56), 3,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDconst,
  [151] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_comment,
    ACTIONS(5), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    ACTIONS(58), 3,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDconst,
  [167] = 2,
    STATE(13), 1,
      sym_comment,
    ACTIONS(60), 6,
      anon_sym_SLASH_STAR,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      anon_sym_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
  [179] = 2,
    STATE(14), 1,
      sym_comment,
    ACTIONS(62), 6,
      anon_sym_SLASH_STAR,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      anon_sym_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
  [191] = 2,
    STATE(15), 1,
      sym_comment,
    ACTIONS(64), 6,
      anon_sym_SLASH_STAR,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      anon_sym_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
  [203] = 4,
    ACTIONS(23), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(29), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    ACTIONS(66), 2,
      aux_sym_comment_token1,
      anon_sym_STAR_STAR,
  [218] = 4,
    ACTIONS(23), 1,
      anon_sym_SLASH_STAR,
    STATE(17), 1,
      sym_comment,
    ACTIONS(29), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
    ACTIONS(68), 2,
      aux_sym_comment_token1,
      anon_sym_STAR_STAR,
  [233] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(18), 1,
      sym_comment,
    ACTIONS(72), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
  [247] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_comment,
    ACTIONS(5), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
  [261] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(76), 1,
      sym_identifier,
    STATE(20), 1,
      sym_comment,
    ACTIONS(72), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
  [275] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(78), 1,
      sym_integer,
    STATE(21), 1,
      sym_comment,
    ACTIONS(5), 2,
      anon_sym_SLASH_STAR_STAR_SLASH,
      anon_sym_SLASH_STAR_STAR_STAR_SLASH,
  [289] = 1,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
  [293] = 1,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
  [297] = 1,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 21,
  [SMALL_STATE(6)] = 42,
  [SMALL_STATE(7)] = 63,
  [SMALL_STATE(8)] = 82,
  [SMALL_STATE(9)] = 103,
  [SMALL_STATE(10)] = 119,
  [SMALL_STATE(11)] = 135,
  [SMALL_STATE(12)] = 151,
  [SMALL_STATE(13)] = 167,
  [SMALL_STATE(14)] = 179,
  [SMALL_STATE(15)] = 191,
  [SMALL_STATE(16)] = 203,
  [SMALL_STATE(17)] = 218,
  [SMALL_STATE(18)] = 233,
  [SMALL_STATE(19)] = 247,
  [SMALL_STATE(20)] = 261,
  [SMALL_STATE(21)] = 275,
  [SMALL_STATE(22)] = 289,
  [SMALL_STATE(23)] = 293,
  [SMALL_STATE(24)] = 297,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_statement, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_statement, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 4, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [74] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_aoe2_rms(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "aoe2_rms",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
